src/Entity/Retrait.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ApiResource()
 * @ORM\Entity(repositoryClass="App\Repository\RetraitRepository")
 */
class Retrait
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Cni;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Montant;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $numeroTransaction;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getCni(): ?string
    {
        return $this->Cni;
    }

    public function setCni(string $Cni): self
    {
        $this->Cni = $Cni;

        return $this;
    }

    public function getMontant(): ?string
    {
        return $this->Montant;
    }

    public function setMontant(string $Montant): self
    {
        $this->Montant = $Montant;

        return $this;
    }

    public function getNumeroTransaction(): ?string
    {
        return $this->numeroTransaction;
    }

    public function setNumeroTransaction(string $numeroTransaction): self
    {
        $this->numeroTransaction = $numeroTransaction;

        return $this;
    }
}

src/Controller/TransactionController.php
<?php

namespace App\Controller;

use App\Entity\Transaction;
use App\Form\Transaction1Type;
use App\Repository\TransactionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/transaction")
 */
class TransactionController extends AbstractController
{
    /**
     * @Route("/", name="transaction_index", methods={"GET"})
     */
    public function index(TransactionRepository $transactionRepository): Response
    {
        return $this->render('transaction/index.html.twig', [
            'transactions' => $transactionRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="transaction_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $transaction = new Transaction();
        $form = $this->createForm(Transaction1Type::class, $transaction);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($transaction);
            $entityManager->flush();

            return $this->redirectToRoute('transaction_index');
        }

        return $this->render('transaction/new.html.twig', [
            'transaction' => $transaction,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="transaction_show", methods={"GET"})
     */
    public function show(Transaction $transaction): Response
    {
        return $this->render('transaction/show.html.twig', [
            'transaction' => $transaction,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="transaction_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Transaction $transaction): Response
    {
        $form = $this->createForm(Transaction1Type::class, $transaction);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('transaction_index');
        }

        return $this->render('transaction/edit.html.twig', [
            'transaction' => $transaction,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="transaction_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Transaction $transaction): Response
    {
        if ($this->isCsrfTokenValid('delete'.$transaction->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($transaction);
            $entityManager->flush();
        }

        return $this->redirectToRoute('transaction_index');
    }
}

templates/transaction/_delete_form.html.twig
<form method="post" action="{{ path('transaction_delete', {'id': transaction.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ transaction.id) }}">
    <button class="btn">Delete</button>
</form>

templates/transaction/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/transaction/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Transaction{% endblock %}

{% block body %}
    <h1>Edit Transaction</h1>

    {{ include('transaction/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('transaction_index') }}">back to list</a>

    {{ include('transaction/_delete_form.html.twig') }}
{% endblock %}

templates/transaction/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Transaction index{% endblock %}

{% block body %}
    <h1>Transaction index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date</th>
                <th>Montant</th>
                <th>Frais</th>
                <th>Numero</th>
                <th>Commission</th>
                <th>Statut</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for transaction in transactions %}
            <tr>
                <td>{{ transaction.id }}</td>
                <td>{{ transaction.date ? transaction.date|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ transaction.montant }}</td>
                <td>{{ transaction.frais }}</td>
                <td>{{ transaction.numero }}</td>
                <td>{{ transaction.commission }}</td>
                <td>{{ transaction.statut }}</td>
                <td>
                    <a href="{{ path('transaction_show', {'id': transaction.id}) }}">show</a>
                    <a href="{{ path('transaction_edit', {'id': transaction.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('transaction_new') }}">Create new</a>
{% endblock %}

templates/transaction/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Transaction{% endblock %}

{% block body %}
    <h1>Create new Transaction</h1>

    {{ include('transaction/_form.html.twig') }}

    <a href="{{ path('transaction_index') }}">back to list</a>
{% endblock %}

templates/transaction/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Transaction{% endblock %}

{% block body %}
    <h1>Transaction</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ transaction.id }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ transaction.date ? transaction.date|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Montant</th>
                <td>{{ transaction.montant }}</td>
            </tr>
            <tr>
                <th>Frais</th>
                <td>{{ transaction.frais }}</td>
            </tr>
            <tr>
                <th>Numero</th>
                <td>{{ transaction.numero }}</td>
            </tr>
            <tr>
                <th>Commission</th>
                <td>{{ transaction.commission }}</td>
            </tr>
            <tr>
                <th>Statut</th>
                <td>{{ transaction.statut }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('transaction_index') }}">back to list</a>

    <a href="{{ path('transaction_edit', {'id': transaction.id}) }}">edit</a>

    {{ include('transaction/_delete_form.html.twig') }}
{% endblock %}